apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test
  namespace: test
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  storageClassName: "rook-ceph-block" # 빈 문자열은 명시적으로 설정해야 하며 그렇지 않으면 기본 스토리지클래스가 설정됨
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
