apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-canary-1.19
  name: nginx-canary-1.19
  namespace: nkkim
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-canary-1.19
      type: canary
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-canary-1.19
        type: canary
    spec:
      containers:
      - image: nginx:1.19
        name: nginx
        resources: {}
status: {}
