apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-canary
  namespace: nkkim
spec:
  replicas: 10 
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-canary
  template:
    metadata:
      labels:
        app: rollout-canary
    spec:
      containers:
      - name: nginx
        image: nginx:1.20
              #- name: rollouts-demo
        #image: argoproj/rollouts-demo:blue
        imagePullPolicy: Always
        ports:
        - containerPort: 80
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 10
      - pause:
          duration: 1m # 1 Miniute
      - setWeight: 20
      - pause: 
          duration: 2m
