apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
  name: nginx-canary
  namespace: nkkim
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    type: canary
status:
  loadBalancer: {}
