apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rollout-bluegreen
  name: nginx-bluegreen
  namespace: nkkim
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rollout-bluegreen
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rollout-bluegreen
    spec:
      containers:
      - image: nginx:1.18
        name: nginx
        resources: {}
status: {}
