apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-blue
  name: nginx-blue
  namespace: nkkim
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-blue
status:
  loadBalancer: {}
