apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rollout-bluegreen
  name: nginx-bluegreen-active
  namespace: nkkim
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
  selector:
    app: rollout-bluegreen
status:
  loadBalancer: {}
