apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rollout-bluegreen
    app: nginx-green
  name: nginx-green
  namespace: nkkim
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rollout-bluegreen
    app: nginx-green
status:
  loadBalancer: {}
