apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
  nameespace: default
data:
  start.sh: |  
              #!/bin/bash
                echo 1
                sleep 10
                echo 2
            