apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  start.sh: |  
              #!/bin/bash
                echo 1
                sleep 10
                echo 2
                echo 3
                echo 4
            