apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-test
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: centos
            image: nkkim/centos-test
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - /start.sh
            volumeMounts:
            - name: cm
              mountPath: /start.sh
              subPath: start.sh
          volumes:
            - name: cm
              configMap:
                name: configmap
                items:
                  - key: start.sh
                    path: start.sh
                    mode: 0777    
          restartPolicy: OnFailure
